apiVersion: apps/v1
kind: Deployment
metadata:
  name: kids
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kids
  template:
    metadata:
      labels:
        app: kids
    spec:
      securityContext:
        runAsUser: 5000
        runAsGroup: 5000
      containers:
        - name: kids
          image: registry.oregon.net.br/celso/kids:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: app_env
            - name: APP_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: app_name
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: app_key
            - name: APP_DEBUG
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: app_debug
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: app_url
            - name: SANCTUM_STATEFUL_DOMAINS
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: sanctum_stateful_domains
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: db_connection
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: db_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: db_port
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: db_database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: db_password
            - name: MAIL_MAILER
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: mail_mailer
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: mail_host
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: mail_port
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: mail_username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: mail_password
            - name: MAIL_ENCRYPTION
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: mail_encryption
            - name: MAIL_FROM_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: mail_from_address
            - name: MAIL_FROM_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets-kids
                  key: mail_from_name
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kids
  namespace: apps
spec:
  selector:
    app: kids
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
